apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-nodejs
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello-nodejs
spec:
  source:
    git:
      url: https://github.com/dbha/hello-nodejs-demo.git
      ref:
        branch: main